const initialLoad = {
  grid: [
    {
      0: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 1,
      },
      1: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 2,
      },
      2: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 3,
      },
      3: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 4,
      },
    },
    {
      0: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 5,
      },
      1: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 6,
      },
      2: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 7,
      },
      3: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 8,
      },
    },
    {
      0: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 9,
      },
      1: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 10,
      },
      2: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 11,
      },
      3: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 12,
      },
    },
    {
      0: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 13,
      },
      1: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 14,
      },
      2: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 15,
      },
      3: {
        species: 0,
        pGRI: 0,
        nGRI: 0,
        pBI: 0,
        plantCount: 0,
        GRiTotal: 0,
        fNear: false,
        wNear: false,
        tileNumber: 16,
      },
    },
  ],
};

module.exports = initialLoad;
